name: laboratory4
description: "211143."

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  table_calendar: ^3.0.9
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  flutter_local_notifications: ^17.2.1
  intl: ^0.18.1
  provider: ^6.1.1
  http: ^1.1.0



  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true
